version: '3.8'

services:
  gateway:
    image: pasindukushan/api-gateway:latest
    container_name: api-gateway_container
    ports:
      - "3000:3000"
    depends_on:
      - auth

  auth:
    image: pasindukushan/auth-service:latest
    container_name: auth-service_container
    ports:
      - "5000:5000"

  frontend:
    image: pasindukushan/frontend:latest
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - gateway
